require 'lolcat/lol'
require 'stringio'
require 'irb'
require "rainbros/version"
require 'rainbros/irb_extensions'
#require 'rainbros/core_extensions'
#require 'rainbros/paint_extensions'
require 'rainbros/lol_cat_extensions'
require 'rainbros/bro_it_out'